Debug = CS.UnityEngine.Debug
UI = CS.UnityEngine.UI
Resources = CS.UnityEngine.Resources
Event = CS.UnityEngine.EventSystems
Color = CS.UnityEngine.Color
Vector3 = CS.UnityEngine.Vector3
Vector2 = CS.UnityEngine.Vector2
Quaternion = CS.UnityEngine.Quaternion
Input = CS.UnityEngine.Input
Time = CS.UnityEngine.Time
PlayerPrefs = CS.UnityEngine.PlayerPrefs
Screen = CS.UnityEngine.Screen
Object = CS.UnityEngine.Object
LayoutRebuilder = CS.UnityEngine.UI.LayoutRebuilder
Enum_Event = CS.Enum_Event
LuaUtil = require("Util/Util")
CBus = CS.CBus.Instance
GameSetting = CS.GameSetting.Instance
HotfixSetting = CS.InstallAndHotfix.HotfixSetting.Instance
DataManager = CBus:GetManager(CS.ManagerName.DataManager, true)
UIManager = CBus:GetManager(CS.ManagerName.UIManager, true)
NoticeManager = CBus:GetManager(CS.ManagerName.NoticeManager, true)
LoadingManager = CBus:GetManager(CS.ManagerName.LoadingManager, true)
ResManager = CBus:GetManager(CS.ManagerName.ResManager, true)
ServerConnectManager = CBus:GetManager(CS.ManagerName.ServerConnectManager, true)
PlotManager = CBus:GetManager(CS.ManagerName.PlotManager, true)
VideoManager = CBus:GetManager(CS.ManagerName.VideoManager, true)
ReplayManager = CBus:GetManager(CS.ManagerName.ReplayManager, true)
SoundManager = CBus:GetManager(CS.ManagerName.SoundManager, true)
CoroutineManager = CBus:GetManager(CS.ManagerName.CoroutineManager, true)
ProtocolFactory = CBus:GetFactory(CS.FactoryName.ProtocolFactory, false, true)
ProtocolType = CS.ServerConnect.Protocol.ProtocolType
UnitFactory = CBus:GetFactory(CS.FactoryName.UnitFactory, false, true)
ItemFactory = CBus:GetFactory(CS.FactoryName.ItemFactory, false, true)
SourceMaterialFactory = CBus:GetFactory(CS.FactoryName.SourceMaterialFactory, false, true)
EquipmentFactory = CBus:GetFactory(CS.FactoryName.EquipmentFactory, false, true)
ItemViewFactory = CBus:GetFactory(CS.FactoryName.ItemViewFactory, false, true)
UnitViewFactory = CBus:GetFactory(CS.FactoryName.UnitViewFactory, false, true)
BreakthroughFactory = CBus:GetFactory(CS.FactoryName.BreakthroughFactory, false, true)
AwakeFactory = CBus:GetFactory(CS.FactoryName.AwakeFactory, false, true)
LevelFactory = CBus:GetFactory(CS.FactoryName.LevelFactory, false, true)
SkillFactory = CBus:GetFactory(CS.FactoryName.SkillFactory, false, true)
PlotFactory = CBus:GetFactory(CS.FactoryName.PlotFactory, false, true)
ParagraphFactory = CBus:GetFactory(CS.FactoryName.ParagraphFactory, false, true)
TalentFactory = CBus:GetFactory(CS.FactoryName.TalentFactory, false, true)
EffectFactory = CBus:GetFactory(CS.FactoryName.EffectFactory, false, true)
EventManager = CBus:GetManager(CS.ManagerName.EventManager, true)
GuideManager = CBus:GetManager(CS.ManagerName.GuideManager, true)
HomeManager = CBus:GetManager(CS.ManagerName.HomeManager, true)
HomeStationStoreManager = CBus:GetManager(CS.ManagerName.HomeStationStoreManager, true)
MainSceneCharacterManager = CBus:GetManager(CS.ManagerName.MainSceneCharacterManager, true)
HomeCoachFactoryManager = CBus:GetManager(CS.ManagerName.HomeCoachFactoryManager, true)
MainManager = CBus:GetManager(CS.ManagerName.MainManager, true)
GuildanceManager = CBus:GetManager(CS.ManagerName.GuildanceManager, true)
TrainCameraManager = CBus:GetManager(CS.ManagerName.TrainCameraManager, true)
HomeCharacterManager = CBus:GetManager(CS.ManagerName.HomeCharacterManager, true)
HomeTrainManager = CBus:GetManager(CS.ManagerName.HomeTrainManager, true)
HomeSceneManager = CBus:GetManager(CS.ManagerName.HomeSceneManager, true)
HomeCreatureManager = CBus:GetManager(CS.ManagerName.HomeCreatureManager, true)
AdvManager = CBus:GetManager(CS.ManagerName.AdvManager, true)
TimelineManager = CBus:GetManager(CS.ManagerName.TimelineManager, true)
TimeLineCameraManager = CBus:GetManager(CS.ManagerName.TimeLineCameraManager, true)
TrainEnvirParamManager = CBus:GetManager(CS.ManagerName.TrainEnvirParamManager, true)
MapSessionManager = CBus:GetManager(CS.ManagerName.MapSessionManager, true)
if IsSimlator then
  G4AirManagerForSimulator = CBus:GetManager(CS.ManagerName.G4AirManagerForSimulator, true)
end
SafeMath = CS.SafeMath
TimeTool = CS.TimeTool
DOTweenTools = CS.DOTweenTools
ParseParagraphScript = CS.ParseParagraphScript
Ease = CS.DG.Tweening.Ease
ExternEdenConsole = CS.ExternEdenConsole
TrainManager = CBus:GetManager(CS.ManagerName.TrainManager, true)
LodAssetLoadManager = CBus:GetManager(CS.ManagerName.LodAssetLoadManager, true)
TrainState = CS.Seven.TrainState
DisplayTrainState = CS.Seven.DisplayTrainState
StrikeState = CS.Seven.StrikeState
File = CS.Seven.FileUtility
