require("CSUsing")
Json = require("vendor/json")
Sort = require("vendor/sort")
MathEx = require("vendor/mathEx")
require("vendor/table")
UIPath = require("UIPathTable")
UIConfig = require("UIConfig")
EnumDefine = require("EnumDefine")
Net = require("Net/Net")
ErrorLog = require("ErrorLog")
PlayerData = require("PlayerData")
TimeUtil = require("Util/TimeUtil")
CommonTips = require("CommonTips")
CommonFilter = require("CommonFilter/CommonFilter")
GuideOrderController = require("Guide/GuideOrderController")
CommonLanguageDef = require("CommonLanguageDef")
ReportTrackEvent = require("ReportTrackEvent")
PosClickHandler = require("PosClickHandler")
Train = require("Train")
HomeUpdateHandler = require("HomeUpdateHandler")
MapEventController = require("UIMapSession/Controller_MapEventController")
UIMainUIController = require("UIMainUI/UIMainUIController")
UITestLevelDataController = require("UITestLevel/UITestLevelDataController")
UIAutoBattle = require("UIAutoBattle/UIAutoBattleViewFunction")
LuaSafeMath = require("Util/SafeMath")
LuaUpdate = require("Base/LuaUpdate")
require("Util/Log")
require("Util/Table_Util")
require("Util/Utility")
require("GetConfig")
require("G4Simlator")
preloadAllFactoryData = false
IsSimlator = false
LuaSetting = require("GameSetting")
require("SimlatorSetting")
AdministrationsAddictionFeature = false
GMTool = require("GMTool")
LevelCheck = require("LevelCheck")
MapNeedleData = require("MapNeedleData")
MapNeedleEventData = require("MapNeedleEventData")
require("Common/StringUtil")
ListenerManager = require("Common/ListenerManager")
RedpointTree = require("Redpoint/RedpointTree").New()
RedPointNodeStr = require("Redpoint/RedPointNodeStr")
CsHelper = require("CS/CsHelper")
CommonHelper = require("Common/CommonHelper")
GameLogicHelper = require("Logic/GameLogicHelper")
SdkHelper = require("SDK/SdkHelper")
QuestTrace = require("Common/QuestTrace")
GameData = require("Data/GameData")
GameMgrs = require("Logic/GameMgrs")
TrainWeaponTag = require("TrainWeaponTag")
HomeFurnitureCollection = require("HomeFurnitureCollection")
CharacterUtil = require("CharacterUtil")
QuestProcess = require("Common/QuestProcess")
return 1
